### ISSUE TITLE
request(kettu):  add Kitsu anime command

### ISSUE THREAD

**Issue by Ruffpuff1** [Ruffpuff1/foxxie#137]
### Which package is the feature request for?

kettu

### Feature

`/kitsu anime [Anime]`

**Comment by ghost** [comment]
Hi @Ruffpuff1 thanks for creating an issue for kettu. I've gone and added a few labels and renamed the issue 🦊🔧.

**Comment by Ruffpuff1** [comment]
using https://kitsu.docs.apiary.io/#reference/anime/fetch-collection?console=1
